In [1]:

import numpy as np
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))
print(a)
print()
print(a.shape)

[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]

(3, 4)


In [2]:

print(a.ravel()) 
print(a.reshape(6, 2)) 
print()
print(a.T) 
print("Transpose shape: ", a.T.shape)
print("Original shape: ", a.shape)

[5. 9. 1. 9. 3. 4. 8. 4. 5. 0. 7. 5.]
[[5. 9.]
 [1. 9.]
 [3. 4.]
 [8. 4.]
 [5. 0.]
 [7. 5.]]

[[5. 3. 5.]
 [9. 4. 0.]
 [1. 8. 7.]
 [9. 4. 5.]]
Transpose shape:  (4, 3)
Original shape:  (3, 4)


In [3]:
print(a)
a.resize((2, 6))
print(a)

[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]
[[5. 9. 1. 9. 3. 4.]
 [8. 4. 5. 0. 7. 5.]]


In [4]:
a.reshape(3, -1)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [5]:
a = np.floor(10 * rg.random((2, 2)))
print(a)
print()
b = np.floor(10 * rg.random((2, 2)))
print(b)
print()
print(np.vstack((a, b))) 
print()
print(np.hstack((a, b)))

[[3. 7.]
 [3. 4.]]

[[1. 4.]
 [2. 2.]]

[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]]

[[3. 7. 1. 4.]
 [3. 4. 2. 2.]]


In [6]:
from numpy import newaxis
print(np.column_stack((a, b)))  
print()
a = np.array([4., 2.])
b = np.array([3., 8.])
print(np.column_stack((a, b))) 
print()
print(np.hstack((a, b)))       
print()
print(a[:, newaxis])           
print()
print(np.column_stack((a[:, newaxis], b[:, newaxis])))
print()
print(np.hstack((a[:, newaxis], b[:, newaxis])))

[[3. 7. 1. 4.]
 [3. 4. 2. 2.]]

[[4. 3.]
 [2. 8.]]

[4. 2. 3. 8.]

[[4.]
 [2.]]

[[4. 3.]
 [2. 8.]]

[[4. 3.]
 [2. 8.]]


In [7]:
np.column_stack is np.hstack

False

In [8]:
np.row_stack is np.vstack

True

In [9]:
print(np.r_[1:4, 0, 4])
print()
print(np.c_[np.array([1,2,3]), np.array([4,5,6])])

[1 2 3 0 4]

[[1 4]
 [2 5]
 [3 6]]


In [10]:
a = np.floor(10 * rg.random((2, 12)))
print(a)
print()
print(np.hsplit(a, 3)) 
print()
print(np.hsplit(a, (3, 4)))

[[7. 2. 4. 9. 9. 7. 5. 2. 1. 9. 5. 1.]
 [6. 7. 6. 9. 0. 5. 4. 0. 6. 8. 5. 2.]]

[array([[7., 2., 4., 9.],
       [6., 7., 6., 9.]]), array([[9., 7., 5., 2.],
       [0., 5., 4., 0.]]), array([[1., 9., 5., 1.],
       [6., 8., 5., 2.]])]

[array([[7., 2., 4.],
       [6., 7., 6.]]), array([[9.],
       [9.]]), array([[9., 7., 5., 2., 1., 9., 5., 1.],
       [0., 5., 4., 0., 6., 8., 5., 2.]])]


In [11]:
a = np.array([[ 0,  1,  2,  3], [ 4,  5,  6,  7], [ 8,  9, 10, 11]])
b = a
print(b is a)

True


In [12]:
def f(x):
  print(id(x))
print(id(a)) 
f(a)

1479352939664
1479352939664


In [13]:
c = a.view()
print(c)
print()
print(c is a)
print()
print(c.base is a)
print()
print(c.flags.owndata)
print()
c = c.reshape((2, 6))
print(c.shape)
print()
print(a.shape)
c[0, 4] = 1234
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

False

True

False

(2, 6)

(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [18]:
s = a[:, 1:3]
print(s)
print()
s[:] = 10  
print(a)

[[10 10]
 [10 10]
 [10 10]]

[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [19]:
d = a.copy()  
print(d is a)
print()
print(d.base is a) 
print()
d[0, 0] = 9999
print(a)

False

False

[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [20]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a